CREATE TABLE game_sessions (
    game_id VARCHAR(100) PRIMARY KEY,
    player_id INT,
    game_state TEXT NOT NULL,
    current_player ENUM('GOAT', 'TIGER'),
    status ENUM('IN_PROGRESS', 'WON', 'LOSS', 'ABORTED') DEFAULT 'IN_PROGRESS',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (player_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);